"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { fetchJson, formatCurrency } from "@/lib/client-utils";
import { AuditLog, Client, Role, Service, User } from "@/lib/types";
import { useSession } from "@/components/SessionProvider";

type ApiList<T> = { role?: Role; data: T[] };
type CreatedUserResponse = {
  role: Role;
  data: User;
  credentials: {
    email: string;
    password: string;
    autoGeneratedEmail: boolean;
    autoGeneratedPassword: boolean;
  };
};
type PasswordResetResponse = {
  role: Role;
  data: {
    id: string;
    email: string;
    password: string;
  };
};

export default function AdminPage() {
  const { role } = useSession();
  const [clients, setClients] = useState<Client[]>([]);
  const [services, setServices] = useState<Service[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [addingClient, setAddingClient] = useState(false);
  const [addingService, setAddingService] = useState(false);
  const [addingUser, setAddingUser] = useState(false);
  const [savingRoleUserId, setSavingRoleUserId] = useState<string | null>(null);
  const [resettingPasswordUserId, setResettingPasswordUserId] = useState<
    string | null
  >(null);
  const [deletingUserId, setDeletingUserId] = useState<string | null>(null);
  const [deletingClientId, setDeletingClientId] = useState<string | null>(null);
  const [deletingServiceId, setDeletingServiceId] = useState<string | null>(null);

  const [clientName, setClientName] = useState("");
  const [serviceForm, setServiceForm] = useState({ name: "", price: 0 });
  const [userForm, setUserForm] = useState<{
    name: string;
    role: Role;
    email: string;
    password: string;
  }>({
    name: "",
    role: "employee",
    email: "",
    password: "",
  });
  const [lastCreatedCredentials, setLastCreatedCredentials] = useState<{
    email: string;
    password: string;
    autoGeneratedEmail: boolean;
    autoGeneratedPassword: boolean;
  } | null>(null);
  const [roleDrafts, setRoleDrafts] = useState<Record<string, Role>>({});

  const canManageMasterData = useMemo(
    () => ["admin", "manager"].includes(role),
    [role],
  );
  const canManageUsers = useMemo(() => role === "admin", [role]);

  const loadAll = useCallback(async () => {
    setLoading(true);
    try {
      const [clientResult, serviceResult, userResult] = await Promise.all([
        fetchJson<ApiList<Client>>("/api/clients"),
        fetchJson<ApiList<Service>>("/api/services"),
        fetchJson<ApiList<User>>("/api/users"),
      ]);

      setClients(clientResult.data);
      setServices(serviceResult.data);
      setUsers(userResult.data);

      if (role === "admin") {
        const auditResult =
          await fetchJson<ApiList<AuditLog>>("/api/audit-logs");
        setAuditLogs(auditResult.data);
      } else {
        setAuditLogs([]);
      }

      setError(null);
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to load admin data",
      );
    } finally {
      setLoading(false);
    }
  }, [role]);

  useEffect(() => {
    const drafts = Object.fromEntries(
      users.map((user) => [user.id, user.role]),
    ) as Record<string, Role>;
    setRoleDrafts(drafts);
  }, [users]);

  useEffect(() => {
    const timer = setTimeout(() => {
      void loadAll();
    }, 0);

    return () => clearTimeout(timer);
  }, [loadAll]);

  async function addClient(event: FormEvent) {
    event.preventDefault();
    setAddingClient(true);
    try {
      await fetchJson("/api/clients", {
        method: "POST",
        body: JSON.stringify({
          name: clientName,
          contact: "",
          company: clientName,
        }),
      });
      setClientName("");
      await loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to add client");
    } finally {
      setAddingClient(false);
    }
  }

  async function addService(event: FormEvent) {
    event.preventDefault();
    setAddingService(true);
    try {
      await fetchJson("/api/services", {
        method: "POST",
        body: JSON.stringify(serviceForm),
      });
      setServiceForm({ name: "", price: 0 });
      await loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to add service");
    } finally {
      setAddingService(false);
    }
  }

  async function deleteClient(id: string) {
    if (!window.confirm("Are you sure you want to delete this client?")) return;
    setDeletingClientId(id);
    try {
      await fetchJson(`/api/clients/${id}`, { method: "DELETE" });
      await loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete client");
    } finally {
      setDeletingClientId(null);
    }
  }

  async function deleteService(id: string) {
    if (!window.confirm("Are you sure you want to delete this service?")) return;
    setDeletingServiceId(id);
    try {
      await fetchJson(`/api/services/${id}`, { method: "DELETE" });
      await loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete service");
    } finally {
      setDeletingServiceId(null);
    }
  }

  async function addUser(event: FormEvent) {
    event.preventDefault();
    setAddingUser(true);
    try {
      const payload: Record<string, unknown> = {
        name: userForm.name,
        role: userForm.role,
      };
      if (userForm.email.trim()) {
        payload.email = userForm.email.trim().toLowerCase();
      }
      if (userForm.password.trim()) {
        payload.password = userForm.password;
      }

      const result = await fetchJson<CreatedUserResponse>("/api/users", {
        method: "POST",
        body: JSON.stringify(payload),
      });
      setUserForm({ name: "", role: "employee", email: "", password: "" });
      setLastCreatedCredentials(result.credentials);
      await loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to add user");
    } finally {
      setAddingUser(false);
    }
  }

  async function saveUserRole(user: User) {
    const nextRole = roleDrafts[user.id] || user.role;
    if (nextRole === user.role) {
      return;
    }

    setSavingRoleUserId(user.id);
    try {
      await fetchJson(`/api/users/${user.id}`, {
        method: "PUT",
        body: JSON.stringify({ role: nextRole }),
      });
      await loadAll();
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to update user role",
      );
    } finally {
      setSavingRoleUserId(null);
    }
  }

  async function resetUserPassword(user: User) {
    setResettingPasswordUserId(user.id);
    try {
      const result = await fetchJson<PasswordResetResponse>(
        `/api/users/${user.id}/reset-password`,
        {
          method: "POST",
        },
      );
      setLastCreatedCredentials({
        email: result.data.email,
        password: result.data.password,
        autoGeneratedEmail: false,
        autoGeneratedPassword: true,
      });
      await loadAll();
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to reset user password",
      );
    } finally {
      setResettingPasswordUserId(null);
    }
  }

  async function deleteUser(user: User) {
    if (!window.confirm(`Are you sure you want to delete user ${user.name}?`)) return;
    setDeletingUserId(user.id);
    try {
      await fetchJson(`/api/users/${user.id}`, { method: "DELETE" });
      await loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete user");
    } finally {
      setDeletingUserId(null);
    }
  }

  return (
    <AppShell
      title="Admin Controls"
      subtitle="Manage clients, services, and team role-based access"
    >
      {error && (
        <div className="mb-6 flex items-start justify-between rounded-xl border border-rose-200 bg-rose-50 dark:bg-rose-950/20 dark:border-rose-900/50 p-3 text-sm text-rose-900 dark:text-rose-200">
          <span>{error}</span>
          <button
            onClick={() => setError(null)}
            className="ml-4 shrink-0 font-bold hover:opacity-70 transition-opacity"
          >
            ✕
          </button>
        </div>
      )}

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Clients Section */}
        <section className="rounded-2xl border border-border bg-card p-5 shadow-sm">
          <h3 className="text-base font-bold text-foreground">Clients</h3>
          {canManageMasterData ? (
            <form onSubmit={addClient} className="mt-4 flex gap-2">
              <input
                className="w-full rounded-xl border border-border bg-background px-3 py-2 text-sm font-medium focus:ring-2 focus:ring-primary outline-none transition-all"
                placeholder="Client name"
                value={clientName}
                onChange={(event) => setClientName(event.target.value)}
                required
                disabled={addingClient}
              />
              <button
                className="rounded-xl bg-foreground text-background px-4 py-2 text-xs font-black uppercase disabled:opacity-50 transition-all hover:opacity-90"
                disabled={addingClient}
              >
                {addingClient ? "…" : "Add"}
              </button>
            </form>
          ) : (
            <p className="mt-3 text-xs font-black uppercase text-slate-900 dark:text-muted-foreground tracking-widest">
              Read-only Access
            </p>
          )}
          <ul className="mt-5 space-y-2">
            {loading
              ? Array.from({ length: 3 }).map((_, i) => (
                  <li
                    key={i}
                    className="animate-pulse rounded-xl bg-muted h-10 w-full"
                  />
                ))
              : clients.map((client) => (
                  <li
                    key={client.id}
                    className="flex items-center justify-between rounded-xl border border-border bg-background px-4 py-2.5 group hover:border-primary/50 transition-colors"
                  >
                    <span className="text-sm font-medium text-foreground">{client.name}</span>
                    {canManageMasterData && (
                      <button
                        className="text-muted-foreground opacity-0 group-hover:opacity-100 hover:text-rose-600 transition-all p-1"
                        onClick={() => deleteClient(client.id)}
                        disabled={deletingClientId === client.id}
                      >
                         <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                        </svg>
                      </button>
                    )}
                  </li>
                ))}
          </ul>
        </section>

        {/* Services Section */}
        <section className="rounded-2xl border border-border bg-card p-5 shadow-sm">
          <h3 className="text-base font-bold text-foreground">Services</h3>
          {canManageMasterData ? (
            <form onSubmit={addService} className="mt-4 space-y-2">
              <input
                className="w-full rounded-xl border border-border bg-background px-3 py-2 text-sm font-medium focus:ring-2 focus:ring-primary outline-none transition-all"
                placeholder="Service name"
                value={serviceForm.name}
                onChange={(event) =>
                  setServiceForm((prev) => ({
                    ...prev,
                    name: event.target.value,
                  }))
                }
                required
                disabled={addingService}
              />
              <div className="flex gap-2">
                <input
                    className="w-full rounded-xl border border-border bg-background px-3 py-2 text-sm font-medium focus:ring-2 focus:ring-primary outline-none transition-all"
                    placeholder="Base Price"
                    type="number"
                    value={serviceForm.price || ""}
                    onChange={(event) =>
                    setServiceForm((prev) => ({
                        ...prev,
                        price: Number(event.target.value),
                    }))
                    }
                    required
                    disabled={addingService}
                />
                <button
                    className="rounded-xl bg-foreground text-background px-4 py-2 text-xs font-black uppercase disabled:opacity-50 transition-all hover:opacity-90"
                    disabled={addingService}
                >
                    {addingService ? "..." : "Add"}
                </button>
              </div>
            </form>
          ) : (
            <p className="mt-3 text-xs font-black uppercase text-slate-900 dark:text-muted-foreground tracking-widest">
              Read-only Access
            </p>
          )}
          <ul className="mt-5 space-y-2">
            {loading
              ? Array.from({ length: 3 }).map((_, i) => (
                  <li
                    key={i}
                    className="animate-pulse rounded-xl bg-muted h-10 w-full"
                  />
                ))
              : services.map((service) => (
                  <li
                    key={service.id}
                    className="flex items-center justify-between rounded-xl border border-border bg-background px-4 py-2.5 group hover:border-primary/50 transition-colors"
                  >
                    <div className="flex flex-col">
                        <span className="text-sm font-bold text-foreground truncate max-w-[140px]">{service.name}</span>
                        <span className="text-[10px] font-black text-muted-foreground uppercase">{formatCurrency(service.price)}</span>
                    </div>
                    {canManageMasterData && (
                      <button
                        className="text-muted-foreground opacity-0 group-hover:opacity-100 hover:text-rose-600 transition-all p-1"
                        onClick={() => deleteService(service.id)}
                        disabled={deletingServiceId === service.id}
                      >
                         <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                        </svg>
                      </button>
                    )}
                  </li>
                ))}
          </ul>
        </section>

        {/* Team Members Section */}
        <section className="rounded-2xl border border-border bg-card p-5 shadow-sm">
          <h3 className="text-base font-bold text-foreground">Team Management</h3>
          {canManageUsers ? (
            <form onSubmit={addUser} className="mt-4 space-y-2">
              <input
                className="w-full rounded-xl border border-border bg-background px-3 py-2 text-sm font-medium focus:ring-2 focus:ring-primary outline-none transition-all"
                placeholder="Full Name"
                value={userForm.name}
                onChange={(event) =>
                  setUserForm((prev) => ({ ...prev, name: event.target.value }))
                }
                required
                disabled={addingUser}
              />
              <div className="grid grid-cols-2 gap-2">
                <input
                    className="w-full rounded-xl border border-border bg-background px-3 py-2 text-sm font-medium focus:ring-2 focus:ring-primary outline-none transition-all"
                    placeholder="Email"
                    type="email"
                    value={userForm.email}
                    onChange={(event) =>
                    setUserForm((prev) => ({
                        ...prev,
                        email: event.target.value,
                    }))
                    }
                    disabled={addingUser}
                />
                <select
                    className="w-full rounded-xl border border-border bg-background px-3 py-2 text-xs font-bold uppercase cursor-pointer focus:ring-2 focus:ring-primary outline-none transition-all"
                    value={userForm.role}
                    onChange={(event) =>
                    setUserForm((prev) => ({
                        ...prev,
                        role: event.target.value as Role,
                    }))
                    }
                    disabled={addingUser}
                >
                    <option value="admin">admin</option>
                    <option value="manager">manager</option>
                    <option value="employee">employee</option>
                </select>
              </div>
              <button
                className="w-full rounded-xl bg-foreground text-background px-4 py-3 text-xs font-black uppercase disabled:opacity-50 transition-all hover:opacity-90 shadow-md"
                disabled={addingUser}
              >
                {addingUser ? "Provisioning…" : "Create User account"}
              </button>
            </form>
          ) : (
            <p className="mt-3 text-xs font-black uppercase text-slate-900 dark:text-muted-foreground tracking-widest">
              Restricted: Admin Only
            </p>
          )}

          {lastCreatedCredentials && (
            <div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 dark:bg-emerald-900/20 dark:border-emerald-900/50 p-4 text-xs">
              <p className="font-black uppercase text-emerald-800 dark:text-emerald-400 mb-2">Success: Credentials Ready</p>
              <div className="space-y-1 font-mono text-emerald-900 dark:text-emerald-300">
                <p><span className="opacity-50">Email:</span> {lastCreatedCredentials.email}</p>
                <p><span className="opacity-50">Pass:</span> {lastCreatedCredentials.password}</p>
              </div>
            </div>
          )}

          <ul className="mt-6 space-y-4">
            {loading
              ? Array.from({ length: 3 }).map((_, i) => (
                  <li
                    key={i}
                    className="animate-pulse rounded-xl bg-muted h-20 w-full"
                  />
                ))
              : users.map((user) => {
                  const selectedRole = roleDrafts[user.id] || user.role;
                  const roleDirty = selectedRole !== user.role;

                  return (
                    <li
                      key={user.id}
                      className="rounded-xl border border-border bg-background p-4 flex flex-col gap-3 group hover:border-primary/50 transition-colors"
                    >
                      <div className="flex flex-col">
                        <span className="text-sm font-bold text-foreground">{user.name}</span>
                        <span className="text-xs text-muted-foreground">{user.email}</span>
                      </div>
                      <div className="flex flex-wrap items-center gap-2 pt-2 border-t border-border">
                        <select
                          className="rounded-lg border border-border bg-muted px-2 py-1 text-[10px] font-black uppercase cursor-pointer outline-none"
                          value={selectedRole}
                          onChange={(event) =>
                            setRoleDrafts((prev) => ({
                              ...prev,
                              [user.id]: event.target.value as Role,
                            }))
                          }
                          disabled={
                            savingRoleUserId === user.id ||
                            resettingPasswordUserId === user.id
                          }
                        >
                          <option value="admin">admin</option>
                          <option value="manager">manager</option>
                          <option value="employee">employee</option>
                        </select>
                        
                        <button
                          className="rounded-lg bg-foreground text-background px-3 py-1 text-[10px] font-black uppercase disabled:opacity-40 transition-all hover:scale-105"
                          onClick={() => saveUserRole(user)}
                          disabled={
                            !roleDirty ||
                            savingRoleUserId === user.id ||
                            resettingPasswordUserId === user.id
                          }
                        >
                          {savingRoleUserId === user.id ? "..." : "Save"}
                        </button>

                        <button
                          className="rounded-lg bg-amber-200 text-amber-950 dark:bg-amber-900/40 dark:text-amber-400 px-4 py-1.5 text-xs font-black uppercase disabled:opacity-40 transition-all ml-auto hover:bg-amber-300 shadow-sm"
                          onClick={() => resetUserPassword(user)}
                          title="Generate New Password"
                          disabled={
                            savingRoleUserId === user.id ||
                            resettingPasswordUserId === user.id
                          }
                        >
                          {resettingPasswordUserId === user.id ? "..." : "Reset"}
                        </button>
                        
                        <button
                          className="rounded-lg bg-rose-200 text-rose-950 dark:bg-rose-950/40 dark:text-rose-400 px-4 py-1.5 text-xs font-black uppercase disabled:opacity-40 transition-all hover:bg-rose-300 shadow-sm"
                          onClick={() => deleteUser(user)}
                          disabled={
                            savingRoleUserId === user.id ||
                            resettingPasswordUserId === user.id ||
                            deletingUserId === user.id
                          }
                        >
                          {deletingUserId === user.id ? "..." : "Delete"}
                        </button>
                      </div>
                    </li>
                  );
                })}
          </ul>
        </section>
      </div>

      {canManageUsers && (
        <section className="mt-8 rounded-2xl border border-border bg-card overflow-hidden shadow-sm">
          <div className="bg-muted px-6 py-4 border-b border-border">
            <h3 className="text-base font-bold text-foreground">Secure System Logs</h3>
          </div>
          <div className="p-2">
            <ul className="divide-y divide-border">
                {loading
                ? Array.from({ length: 4 }).map((_, i) => (
                    <li
                        key={i}
                        className="animate-pulse rounded px-4 py-4"
                    >
                         <div className="h-4 bg-muted rounded w-3/4"></div>
                    </li>
                    ))
                : auditLogs.slice(0, 15).map((entry) => (
                    <li key={entry.id} className="px-5 py-3 hover:bg-muted/30 transition-colors flex items-center gap-4 text-xs font-medium">
                        <span className="rounded-lg bg-zinc-200 dark:bg-zinc-800 px-2 py-1 font-black uppercase text-[10px] text-slate-900 dark:text-muted-foreground w-20 text-center shrink-0">
                            {formatDate(entry.created_at).split(' ')[0]}
                        </span>
                        <div className="flex-1 min-w-0">
                            <span className="font-bold text-slate-900 dark:text-foreground">{entry.action}</span>
                            <span className="mx-2 opacity-30">|</span>
                            <span className="text-slate-700 dark:text-muted-foreground italic truncate">{entry.details}</span>
                        </div>
                        <span className="text-[10px] font-bold text-slate-600 dark:text-muted-foreground opacity-70 shrink-0">
                            BY {entry.actor_email}
                        </span>
                    </li>
                    ))}
            </ul>
          </div>
        </section>
      )}
    </AppShell>
  );
}
