"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { fetchJson, formatCurrency, formatDate } from "@/lib/client-utils";
import { AuditLog, Client, Role, Service, User } from "@/lib/types";
import { useSession } from "@/components/SessionProvider";
import { useOffline } from "@/components/OfflineProvider";
import { motion, AnimatePresence } from "framer-motion";

type ApiList<T> = { role?: Role; data: T[] };
type CreatedUserResponse = {
  role: Role;
  data: User;
  credentials: {
    email: string;
    password: string;
    autoGeneratedEmail: boolean;
    autoGeneratedPassword: boolean;
  };
};
type PasswordResetResponse = {
  role: Role;
  data: {
    id: string;
    email: string;
    password: string;
  };
};

export default function AdminPage() {
  const { role } = useSession();
  const { isOffline } = useOffline();
  const [clients, setClients] = useState<Client[]>([]);
  const [services, setServices] = useState<Service[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [addingClient, setAddingClient] = useState(false);
  const [addingService, setAddingService] = useState(false);
  const [addingUser, setAddingUser] = useState(false);
  const [savingRoleUserId, setSavingRoleUserId] = useState<string | null>(null);
  const [resettingPasswordUserId, setResettingPasswordUserId] = useState<
    string | null
  >(null);
  const [deletingUserId, setDeletingUserId] = useState<string | null>(null);
  const [deletingClientId, setDeletingClientId] = useState<string | null>(null);
  const [deletingServiceId, setDeletingServiceId] = useState<string | null>(null);

  const [clientName, setClientName] = useState("");
  const [serviceForm, setServiceForm] = useState({ name: "", price: 0 });
  const [userForm, setUserForm] = useState<{
    name: string;
    role: Role;
    email: string;
    password: string;
  }>({
    name: "",
    role: "employee",
    email: "",
    password: "",
  });
  const [lastCreatedCredentials, setLastCreatedCredentials] = useState<{
    email: string;
    password: string;
    autoGeneratedEmail: boolean;
    autoGeneratedPassword: boolean;
  } | null>(null);
  const [roleDrafts, setRoleDrafts] = useState<Record<string, Role>>({});

  const canManageMasterData = useMemo(
    () => ["admin", "manager"].includes(role),
    [role],
  );
  const canManageUsers = useMemo(() => role === "admin", [role]);

  const loadAll = useCallback(async () => {
    setLoading(true);
    try {
      const [clientResult, serviceResult, userResult] = await Promise.all([
        fetchJson<ApiList<Client>>("/api/clients"),
        fetchJson<ApiList<Service>>("/api/services"),
        fetchJson<ApiList<User>>("/api/users"),
      ]);

      setClients(clientResult.data);
      setServices(serviceResult.data);
      setUsers(userResult.data);

      if (role === "admin") {
        const auditResult =
          await fetchJson<ApiList<AuditLog>>("/api/audit-logs");
        setAuditLogs(auditResult.data);
      } else {
        setAuditLogs([]);
      }

      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load admin data");
    } finally {
      setLoading(false);
    }
  }, [role]);

  useEffect(() => {
    loadAll();
  }, [loadAll]);

  // Master Data Handlers
  async function addClient(e: FormEvent) {
    e.preventDefault();
    if (!clientName.trim()) return;
    setAddingClient(true);
    try {
      await fetchJson("/api/clients", {
        method: "POST",
        body: JSON.stringify({ name: clientName }),
      });
      setClientName("");
      loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to add client");
    } finally {
      setAddingClient(false);
    }
  }

  async function deleteClient(id: string) {
    if (!confirm("Are you sure? This may affect linked income records.")) return;
    setDeletingClientId(id);
    try {
      await fetchJson(`/api/clients/${id}`, { method: "DELETE" });
      loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete client");
    } finally {
      setDeletingClientId(null);
    }
  }

  async function addService(e: FormEvent) {
    e.preventDefault();
    if (!serviceForm.name.trim()) return;
    setAddingService(true);
    try {
      await fetchJson("/api/services", {
        method: "POST",
        body: JSON.stringify(serviceForm),
      });
      setServiceForm({ name: "", price: 0 });
      loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to add service");
    } finally {
      setAddingService(false);
    }
  }

  async function deleteService(id: string) {
    if (!confirm("Are you sure?")) return;
    setDeletingServiceId(id);
    try {
      await fetchJson(`/api/services/${id}`, { method: "DELETE" });
      loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete service");
    } finally {
      setDeletingServiceId(null);
    }
  }

  // User Management
  async function createUser(e: FormEvent) {
    e.preventDefault();
    setAddingUser(true);
    try {
      const res = await fetchJson<CreatedUserResponse>("/api/users", {
        method: "POST",
        body: JSON.stringify(userForm),
      });
      setUserForm({ name: "", role: "employee", email: "", password: "" });
      setLastCreatedCredentials(res.credentials);
      loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create user");
    } finally {
      setAddingUser(false);
    }
  }

  function handleRoleChange(userId: string, role: Role) {
    setRoleDrafts(prev => ({ ...prev, [userId]: role }));
  }

  async function saveUserRole(user: User) {
    const newRole = roleDrafts[user.id];
    if (!newRole) return;
    setSavingRoleUserId(user.id);
    try {
      await fetchJson(`/api/users/${user.id}/role`, {
        method: "PUT",
        body: JSON.stringify({ role: newRole }),
      });
      const newDrafts = { ...roleDrafts };
      delete newDrafts[user.id];
      setRoleDrafts(newDrafts);
      loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to update role");
    } finally {
      setSavingRoleUserId(null);
    }
  }

  async function resetUserPassword(user: User) {
    if (!confirm(`Reset password for ${user.name}?`)) return;
    setResettingPasswordUserId(user.id);
    try {
      const res = await fetchJson<PasswordResetResponse>(`/api/users/${user.id}/reset-password`, {
        method: "POST"
      });
      setLastCreatedCredentials({
        email: res.data.email,
        password: res.data.password,
        autoGeneratedEmail: false,
        autoGeneratedPassword: true
      });
      loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to reset password");
    } finally {
      setResettingPasswordUserId(null);
    }
  }

  async function deleteUser(user: User) {
    if (!confirm(`Permanently delete user ${user.name}? This cannot be undone.`)) return;
    setDeletingUserId(user.id);
    try {
      await fetchJson(`/api/users/${user.id}`, { method: "DELETE" });
      loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete user");
    } finally {
      setDeletingUserId(null);
    }
  }

  if (!canManageMasterData) {
    return (
      <AppShell title="Admin" subtitle="Access Denied">
        <div className="p-6 text-center text-slate-500">You do not have permission to access the administrative panel.</div>
      </AppShell>
    );
  }

  return (
    <AppShell title="Administrative Center" subtitle="Control system settings, users, and master data catalogs">
      {error && (
        <div className="mb-8 rounded-2xl border border-rose-200 bg-rose-50 dark:bg-rose-950/20 dark:border-rose-900/50 p-4 text-sm text-rose-900 dark:text-rose-200 flex items-center justify-between shadow-xl">
          <span>{error}</span>
          <button onClick={() => setError(null)} className="ml-4 font-black uppercase text-[10px] hover:opacity-70 transition-opacity">Dismiss</button>
        </div>
      )}

      {lastCreatedCredentials && (
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="mb-8 rounded-3xl border-2 border-emerald-500/30 bg-emerald-50/50 p-6 shadow-2xl backdrop-blur-md dark:bg-emerald-950/20"
        >
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-black uppercase tracking-widest text-emerald-700 dark:text-emerald-400">Account Credentials Generated</h3>
            <button onClick={() => setLastCreatedCredentials(null)} className="text-emerald-800 dark:text-emerald-500 font-black">✕</button>
          </div>
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="rounded-xl bg-white/50 dark:bg-emerald-950/50 p-4 border border-emerald-500/10">
              <p className="text-[10px] uppercase font-black text-emerald-600/60 mb-1">Email</p>
              <p className="font-mono text-sm font-bold text-emerald-900 dark:text-emerald-100">{lastCreatedCredentials.email}</p>
            </div>
            <div className="rounded-xl bg-white/50 dark:bg-emerald-950/50 p-4 border border-emerald-500/10">
              <p className="text-[10px] uppercase font-black text-emerald-600/60 mb-1">Temporary Password</p>
              <p className="font-mono text-sm font-bold text-emerald-900 dark:text-emerald-100">{lastCreatedCredentials.password}</p>
            </div>
          </div>
          <p className="mt-4 text-xs font-medium text-emerald-800 dark:text-emerald-400 italic">Please share these credentials securely. The password will not be shown again.</p>
        </motion.div>
      )}

      <div className="grid gap-8 lg:grid-cols-2">
        {/* Clients & Services */}
        <div className="space-y-8">
          <motion.section 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-3xl glass-card overflow-hidden shadow-2xl"
          >
            <div className="glass-header px-6 py-4 flex items-center gap-2 border-b border-border/30">
               <svg className="h-4 w-4 text-primary" fill="currentColor" viewBox="0 0 20 20"><path d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z" /></svg>
               <h3 className="text-sm font-black uppercase tracking-widest text-foreground">Client Catalog</h3>
            </div>
            <div className="p-6">
              <form onSubmit={addClient} className="flex gap-2 mb-6">
                <input
                  className="flex-1 rounded-xl border border-border/50 bg-background/50 px-4 py-2 text-sm font-bold focus:ring-2 focus:ring-primary outline-none transition-all"
                  placeholder="Official Client Name"
                  value={clientName}
                  onChange={(e) => setClientName(e.target.value)}
                  disabled={addingClient || isOffline}
                />
                <button
                  className="glass-btn glass-btn-primary px-4 py-2"
                  disabled={addingClient || isOffline}
                >
                  {addingClient ? "…" : "Add"}
                </button>
              </form>
              <div className="max-h-60 overflow-y-auto pr-2 space-y-2 no-scrollbar">
                {clients.map((c) => (
                  <div key={c.id} className="flex items-center justify-between rounded-xl bg-white/30 dark:bg-white/5 p-3 border border-white/10 group transition-all hover:bg-white/50 dark:hover:bg-white/10">
                    <span className="text-sm font-bold text-foreground">{c.name}</span>
                    <button
                      className="opacity-0 group-hover:opacity-100 text-rose-500 hover:text-rose-600 transition-all font-black text-[10px] uppercase tracking-widest"
                      onClick={() => deleteClient(c.id)}
                      disabled={deletingClientId === c.id || isOffline}
                    >
                      {deletingClientId === c.id ? "…" : "Delete"}
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </motion.section>

          <motion.section 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="rounded-3xl glass-card overflow-hidden shadow-2xl"
          >
            <div className="glass-header px-6 py-4 flex items-center gap-2 border-b border-border/30">
               <svg className="h-4 w-4 text-primary" fill="currentColor" viewBox="0 0 20 20"><path d="M7 3a1 1 0 000 2h6a1 1 0 100-2H7zM4 7a1 1 0 011-1h10a1 1 0 110 2H5a1 1 0 01-1-1zM2 11a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 01-2 2H4a2 2 0 01-2-2v-4z" /></svg>
               <h3 className="text-sm font-black uppercase tracking-widest text-foreground">Service Catalog</h3>
            </div>
            <div className="p-6">
              <form onSubmit={addService} className="grid grid-cols-1 sm:grid-cols-12 gap-2 mb-6">
                <input
                    className="sm:col-span-7 rounded-xl border border-border/50 bg-background/50 px-4 py-2 text-sm font-bold focus:ring-2 focus:ring-primary outline-none transition-all"
                    placeholder="Service Type"
                    value={serviceForm.name}
                    onChange={(e) => setServiceForm(prev => ({ ...prev, name: e.target.value }))}
                />
                <input
                    className="sm:col-span-3 rounded-xl border border-border/50 bg-background/50 px-4 py-2 text-sm font-bold focus:ring-2 focus:ring-primary outline-none transition-all"
                    type="number"
                    placeholder="Price"
                    value={serviceForm.price || ""}
                    onChange={(e) => setServiceForm(prev => ({ ...prev, price: Number(e.target.value) }))}
                />
                <button
                    className="sm:col-span-2 glass-btn glass-btn-primary px-4 py-2"
                    disabled={addingService || isOffline}
                >
                    {addingService ? "..." : "Add"}
                </button>
              </form>
              <div className="max-h-60 overflow-y-auto pr-2 space-y-2 no-scrollbar">
                {services.map((s) => (
                  <div key={s.id} className="flex items-center justify-between rounded-xl bg-white/30 dark:bg-white/5 p-3 border border-white/10 group transition-all hover:bg-white/50 dark:hover:bg-white/10">
                    <div className="flex flex-col">
                      <span className="text-sm font-bold text-foreground">{s.name}</span>
                      <span className="text-[10px] font-black uppercase text-primary/60">{formatCurrency(s.price)}</span>
                    </div>
                    <button
                      className="opacity-0 group-hover:opacity-100 text-rose-500 hover:text-rose-600 transition-all font-black text-[10px] uppercase tracking-widest"
                      onClick={() => deleteService(s.id)}
                      disabled={deletingServiceId === s.id || isOffline}
                    >
                      {deletingServiceId === s.id ? "…" : "Delete"}
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </motion.section>
        </div>

        {/* User Management */}
        <div className="space-y-8">
          {canManageUsers && (
            <motion.section 
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              className="rounded-3xl glass-card overflow-hidden shadow-2xl"
            >
              <div className="glass-header px-6 py-4 flex items-center gap-2 border-b border-border/30">
                <svg className="h-4 w-4 text-primary" fill="currentColor" viewBox="0 0 20 20"><path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z" /></svg>
                <h3 className="text-sm font-black uppercase tracking-widest text-foreground">Identity & Access</h3>
              </div>
              <div className="p-6">
                <form onSubmit={createUser} className="space-y-4">
                  <div className="grid gap-4 sm:grid-cols-2">
                    <div className="space-y-1">
                      <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground ml-1">Full Name</label>
                      <input
                        className="w-full rounded-xl border border-border/50 bg-background/50 px-4 py-2.5 text-sm font-bold focus:ring-2 focus:ring-primary outline-none transition-all"
                        placeholder="e.g. Rudresh Vyas"
                        value={userForm.name}
                        onChange={(e) => setUserForm(prev => ({ ...prev, name: e.target.value }))}
                        required
                      />
                    </div>
                    <div className="space-y-1">
                      <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground ml-1">System Role</label>
                      <select
                        className="w-full rounded-xl border border-border/50 bg-background/50 px-4 py-2.5 text-sm font-bold focus:ring-2 focus:ring-primary outline-none transition-all cursor-pointer backdrop-blur-sm"
                        value={userForm.role}
                        onChange={(e) => setUserForm(prev => ({ ...prev, role: e.target.value as Role }))}
                      >
                        <option value="admin">Admin</option>
                        <option value="manager">Manager</option>
                        <option value="employee">Employee</option>
                      </select>
                    </div>
                  </div>
                  <div className="space-y-1">
                    <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground ml-1">Login Identity (Email or Phone)</label>
                    <input
                      className="w-full rounded-xl border border-border/50 bg-background/50 px-4 py-2.5 text-sm font-bold focus:ring-2 focus:ring-primary outline-none transition-all"
                      placeholder="e.g. admin@bizzgrow.com"
                      value={userForm.email}
                      onChange={(e) => setUserForm(prev => ({ ...prev, email: e.target.value }))}
                    />
                    <p className="text-[9px] text-muted-foreground mt-1 tracking-wide">Enter an email, or leave blank to generate a system identity.</p>
                  </div>
                  <div className="space-y-1">
                    <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground ml-1">Initial Password</label>
                    <input
                      className="w-full rounded-xl border border-border/50 bg-background/50 px-4 py-2.5 text-sm font-bold focus:ring-2 focus:ring-primary outline-none transition-all"
                      type="password"
                      placeholder="Leave blank to auto-generate"
                      value={userForm.password}
                      onChange={(e) => setUserForm(prev => ({ ...prev, password: e.target.value }))}
                    />
                  </div>
                  <button
                    className="w-full glass-btn glass-btn-primary py-4 mt-2 shadow-xl"
                    disabled={addingUser || isOffline}
                  >
                    {addingUser ? "Provisioning…" : "Create User account"}
                  </button>
                </form>

                <div className="mt-8">
                  <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground mb-4">Total Workforce ({users.length})</h4>
                  <ul className="space-y-3">
                    {users.map((user) => {
                      const roleDraft = roleDrafts[user.id];
                      const roleDirty = roleDraft && roleDraft !== user.role;
                      return (
                        <li key={user.id} className="rounded-2xl border border-border/30 bg-white/40 dark:bg-white/5 p-4 transition-all hover:bg-white/60 dark:hover:bg-white/10">
                          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                            <div>
                              <p className="text-sm font-black text-foreground">{user.name}</p>
                              <p className="text-[10px] font-medium text-muted-foreground">{user.email}</p>
                            </div>
                            <div className="flex flex-wrap items-center gap-2">
                              <select
                                className="rounded-lg border border-border/40 bg-background/50 px-2 py-1.5 text-[10px] font-bold outline-none cursor-pointer"
                                value={roleDraft || user.role}
                                onChange={(e) => handleRoleChange(user.id, e.target.value as Role)}
                              >
                                <option value="admin">admin</option>
                                <option value="manager">manager</option>
                                <option value="employee">employee</option>
                              </select>
                              
                               <button
                                 className={`glass-btn px-3 py-1.5 transition-all ${
                                   roleDirty ? 'glass-btn-primary shadow-lg scale-105' : 'glass-btn-secondary opacity-40'
                                 }`}
                                 onClick={() => saveUserRole(user)}
                                 disabled={
                                   !roleDirty ||
                                   savingRoleUserId === user.id ||
                                   resettingPasswordUserId === user.id
                                 }
                               >
                                 {savingRoleUserId === user.id ? "..." : "Save"}
                               </button>

                               <button
                                 className="glass-btn glass-btn-secondary px-3 py-1.5 text-[8px] border-amber-500/20 text-amber-600 ml-auto"
                                 onClick={() => resetUserPassword(user)}
                                 title="Generate New Password"
                                 disabled={
                                   savingRoleUserId === user.id ||
                                   resettingPasswordUserId === user.id ||
                                   isOffline
                                 }
                               >
                                 {resettingPasswordUserId === user.id ? "..." : "Reset"}
                               </button>
                               
                               <button
                                 className="glass-btn glass-btn-danger px-3 py-1.5 text-[8px]"
                                 onClick={() => deleteUser(user)}
                                 disabled={
                                   savingRoleUserId === user.id ||
                                   resettingPasswordUserId === user.id ||
                                   deletingUserId === user.id ||
                                   isOffline
                                 }
                               >
                                 {deletingUserId === user.id ? "..." : "Delete"}
                               </button>
                            </div>
                          </div>
                        </li>
                      );
                    })}
                  </ul>
                </div>
              </div>
            </motion.section>
          )}

          {role === "admin" && (
            <motion.section 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="rounded-3xl glass-card overflow-hidden shadow-2xl"
            >
               <div className="glass-header px-6 py-4 flex items-center gap-2 border-b border-border/30">
                <svg className="h-4 w-4 text-primary" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zM11 17a1 1 0 10-2 0v1a1 1 0 102 0v-1zM4.222 19.071a1 1 0 010-1.414l.707-.707a1 1 0 011.414 1.414l-.707.707a1 1 0 01-1.414 0zM3.707 5.364a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414l-.707.707zM3 11a1 1 0 100-2H2a1 1 0 100 2h1z" clipRule="evenodd" /></svg>
                <h3 className="text-sm font-black uppercase tracking-widest text-foreground">Security Audit Trail</h3>
              </div>
              <div className="p-6">
                <div className="max-h-96 overflow-y-auto pr-2 space-y-3 no-scrollbar">
                  {auditLogs.map((log) => (
                    <div key={log.id} className="rounded-xl bg-white/30 dark:bg-white/5 p-3 border border-white/10 text-[11px]">
                      <div className="flex justify-between items-start mb-1 text-muted-foreground uppercase font-black tracking-widest text-[9px]">
                        <span>{log.user_name}</span>
                        <span>{formatDate(log.created_at)}</span>
                      </div>
                      <p className="text-foreground font-bold line-clamp-2">{log.action}</p>
                    </div>
                  ))}
                  {auditLogs.length === 0 && (
                    <p className="text-center text-muted-foreground italic py-8">No security logs recorded.</p>
                  )}
                </div>
              </div>
            </motion.section>
          )}
        </div>
      </div>
    </AppShell>
  );
}
