"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { fetchJson, formatCurrency } from "@/lib/client-utils";
import { AuditLog, Client, Role, Service, User } from "@/lib/types";
import { useSession } from "@/components/SessionProvider";

type ApiList<T> = { role?: Role; data: T[] };
type CreatedUserResponse = {
  role: Role;
  data: User;
  credentials: {
    email: string;
    password: string;
    autoGeneratedEmail: boolean;
    autoGeneratedPassword: boolean;
  };
};
type PasswordResetResponse = {
  role: Role;
  data: {
    id: string;
    email: string;
    password: string;
  };
};

export default function AdminPage() {
  const { role } = useSession();
  const [clients, setClients] = useState<Client[]>([]);
  const [services, setServices] = useState<Service[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [addingClient, setAddingClient] = useState(false);
  const [addingService, setAddingService] = useState(false);
  const [addingUser, setAddingUser] = useState(false);
  const [savingRoleUserId, setSavingRoleUserId] = useState<string | null>(null);
  const [resettingPasswordUserId, setResettingPasswordUserId] = useState<
    string | null
  >(null);
  const [deletingUserId, setDeletingUserId] = useState<string | null>(null);
  const [deletingClientId, setDeletingClientId] = useState<string | null>(null);
  const [deletingServiceId, setDeletingServiceId] = useState<string | null>(null);

  const [clientName, setClientName] = useState("");
  const [serviceForm, setServiceForm] = useState({ name: "", price: 0 });
  const [userForm, setUserForm] = useState<{
    name: string;
    role: Role;
    email: string;
    password: string;
  }>({
    name: "",
    role: "employee",
    email: "",
    password: "",
  });
  const [lastCreatedCredentials, setLastCreatedCredentials] = useState<{
    email: string;
    password: string;
    autoGeneratedEmail: boolean;
    autoGeneratedPassword: boolean;
  } | null>(null);
  const [roleDrafts, setRoleDrafts] = useState<Record<string, Role>>({});

  const canManageMasterData = useMemo(
    () => ["admin", "manager"].includes(role),
    [role],
  );
  const canManageUsers = useMemo(() => role === "admin", [role]);

  const loadAll = useCallback(async () => {
    setLoading(true);
    try {
      const [clientResult, serviceResult, userResult] = await Promise.all([
        fetchJson<ApiList<Client>>("/api/clients"),
        fetchJson<ApiList<Service>>("/api/services"),
        fetchJson<ApiList<User>>("/api/users"),
      ]);

      setClients(clientResult.data);
      setServices(serviceResult.data);
      setUsers(userResult.data);

      if (role === "admin") {
        const auditResult =
          await fetchJson<ApiList<AuditLog>>("/api/audit-logs");
        setAuditLogs(auditResult.data);
      } else {
        setAuditLogs([]);
      }

      setError(null);
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to load admin data",
      );
    } finally {
      setLoading(false);
    }
  }, [role]);

  useEffect(() => {
    const drafts = Object.fromEntries(
      users.map((user) => [user.id, user.role]),
    ) as Record<string, Role>;
    setRoleDrafts(drafts);
  }, [users]);

  useEffect(() => {
    const timer = setTimeout(() => {
      void loadAll();
    }, 0);

    return () => clearTimeout(timer);
  }, [loadAll]);

  async function addClient(event: FormEvent) {
    event.preventDefault();
    setAddingClient(true);
    try {
      await fetchJson("/api/clients", {
        method: "POST",
        body: JSON.stringify({
          name: clientName,
          contact: "",
          company: clientName,
        }),
      });
      setClientName("");
      await loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to add client");
    } finally {
      setAddingClient(false);
    }
  }

  async function addService(event: FormEvent) {
    event.preventDefault();
    setAddingService(true);
    try {
      await fetchJson("/api/services", {
        method: "POST",
        body: JSON.stringify(serviceForm),
      });
      setServiceForm({ name: "", price: 0 });
      await loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to add service");
    } finally {
      setAddingService(false);
    }
  }

  async function deleteClient(id: string) {
    if (!window.confirm("Are you sure you want to delete this client?")) return;
    setDeletingClientId(id);
    try {
      await fetchJson(`/api/clients/${id}`, { method: "DELETE" });
      await loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete client");
    } finally {
      setDeletingClientId(null);
    }
  }

  async function deleteService(id: string) {
    if (!window.confirm("Are you sure you want to delete this service?")) return;
    setDeletingServiceId(id);
    try {
      await fetchJson(`/api/services/${id}`, { method: "DELETE" });
      await loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete service");
    } finally {
      setDeletingServiceId(null);
    }
  }

  async function addUser(event: FormEvent) {
    event.preventDefault();
    setAddingUser(true);
    try {
      const payload: Record<string, unknown> = {
        name: userForm.name,
        role: userForm.role,
      };
      if (userForm.email.trim()) {
        payload.email = userForm.email.trim().toLowerCase();
      }
      if (userForm.password.trim()) {
        payload.password = userForm.password;
      }

      const result = await fetchJson<CreatedUserResponse>("/api/users", {
        method: "POST",
        body: JSON.stringify(payload),
      });
      setUserForm({ name: "", role: "employee", email: "", password: "" });
      setLastCreatedCredentials(result.credentials);
      await loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to add user");
    } finally {
      setAddingUser(false);
    }
  }

  async function saveUserRole(user: User) {
    const nextRole = roleDrafts[user.id] || user.role;
    if (nextRole === user.role) {
      return;
    }

    setSavingRoleUserId(user.id);
    try {
      await fetchJson(`/api/users/${user.id}`, {
        method: "PUT",
        body: JSON.stringify({ role: nextRole }),
      });
      await loadAll();
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to update user role",
      );
    } finally {
      setSavingRoleUserId(null);
    }
  }

  async function resetUserPassword(user: User) {
    setResettingPasswordUserId(user.id);
    try {
      const result = await fetchJson<PasswordResetResponse>(
        `/api/users/${user.id}/reset-password`,
        {
          method: "POST",
        },
      );
      setLastCreatedCredentials({
        email: result.data.email,
        password: result.data.password,
        autoGeneratedEmail: false,
        autoGeneratedPassword: true,
      });
      await loadAll();
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to reset user password",
      );
    } finally {
      setResettingPasswordUserId(null);
    }
  }

  async function deleteUser(user: User) {
    if (!window.confirm(`Are you sure you want to delete user ${user.name}?`)) return;
    setDeletingUserId(user.id);
    try {
      await fetchJson(`/api/users/${user.id}`, { method: "DELETE" });
      await loadAll();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete user");
    } finally {
      setDeletingUserId(null);
    }
  }

  return (
    <AppShell
      title="Admin Controls"
      subtitle="Manage clients, services, and team role-based access"
    >
      {error && (
        <div className="mb-4 flex items-start justify-between rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-900">
          <span>{error}</span>
          <button
            onClick={() => setError(null)}
            className="ml-4 shrink-0 font-semibold hover:text-rose-700"
          >
            ✕
          </button>
        </div>
      )}

      <div className="grid gap-4 lg:grid-cols-3">
        <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
          <h3 className="text-base font-semibold">Clients</h3>
          {canManageMasterData ? (
            <form onSubmit={addClient} className="mt-3 flex gap-2">
              <input
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                placeholder="Client name"
                value={clientName}
                onChange={(event) => setClientName(event.target.value)}
                required
                disabled={addingClient}
              />
              <button
                className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50"
                disabled={addingClient}
              >
                {addingClient ? "…" : "Add"}
              </button>
            </form>
          ) : (
            <p className="mt-3 text-xs text-slate-500">
              Read-only for your role.
            </p>
          )}
          <ul className="mt-3 space-y-2 text-sm">
            {loading
              ? Array.from({ length: 3 }).map((_, i) => (
                  <li
                    key={i}
                    className="animate-pulse rounded-lg bg-slate-200 px-3 py-4"
                  />
                ))
              : clients.map((client) => (
                  <li
                    key={client.id}
                    className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2"
                  >
                    <span>{client.name}</span>
                    {canManageMasterData && (
                      <button
                        className="text-rose-600 hover:text-rose-800 disabled:opacity-50"
                        onClick={() => deleteClient(client.id)}
                        disabled={deletingClientId === client.id}
                        title="Delete Client"
                      >
                        ✕
                      </button>
                    )}
                  </li>
                ))}
          </ul>
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
          <h3 className="text-base font-semibold">Services</h3>
          {canManageMasterData ? (
            <form onSubmit={addService} className="mt-3 space-y-2">
              <input
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                placeholder="Service name"
                value={serviceForm.name}
                onChange={(event) =>
                  setServiceForm((prev) => ({
                    ...prev,
                    name: event.target.value,
                  }))
                }
                required
                disabled={addingService}
              />
              <input
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                placeholder="Default price"
                type="number"
                value={serviceForm.price || ""}
                onChange={(event) =>
                  setServiceForm((prev) => ({
                    ...prev,
                    price: Number(event.target.value),
                  }))
                }
                required
                disabled={addingService}
              />
              <button
                className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50"
                disabled={addingService}
              >
                {addingService ? "Saving..." : "Add"}
              </button>
            </form>
          ) : (
            <p className="mt-3 text-xs text-slate-500">
              Read-only for your role.
            </p>
          )}
          <ul className="mt-3 space-y-2 text-sm">
            {loading
              ? Array.from({ length: 3 }).map((_, i) => (
                  <li
                    key={i}
                    className="animate-pulse rounded-lg bg-slate-200 px-3 py-4"
                  />
                ))
              : services.map((service) => (
                  <li
                    key={service.id}
                    className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2"
                  >
                    <span className="truncate">{service.name} - {formatCurrency(service.price)}</span>
                    {canManageMasterData && (
                      <button
                        className="text-rose-600 hover:text-rose-800 disabled:opacity-50"
                        onClick={() => deleteService(service.id)}
                        disabled={deletingServiceId === service.id}
                        title="Delete Service"
                      >
                        ✕
                      </button>
                    )}
                  </li>
                ))}
          </ul>
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
          <h3 className="text-base font-semibold">Team Members</h3>
          {canManageUsers ? (
            <form onSubmit={addUser} className="mt-3 space-y-2">
              <input
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                placeholder="Name"
                value={userForm.name}
                onChange={(event) =>
                  setUserForm((prev) => ({ ...prev, name: event.target.value }))
                }
                required
                disabled={addingUser}
              />
              <input
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                placeholder="Email (optional)"
                type="email"
                value={userForm.email}
                onChange={(event) =>
                  setUserForm((prev) => ({
                    ...prev,
                    email: event.target.value,
                  }))
                }
                disabled={addingUser}
              />
              <input
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                placeholder="Password (optional, min 8 chars)"
                type="text"
                minLength={8}
                value={userForm.password}
                onChange={(event) =>
                  setUserForm((prev) => ({
                    ...prev,
                    password: event.target.value,
                  }))
                }
                disabled={addingUser}
              />
              <select
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                value={userForm.role}
                onChange={(event) =>
                  setUserForm((prev) => ({
                    ...prev,
                    role: event.target.value as Role,
                  }))
                }
                disabled={addingUser}
              >
                <option value="admin">admin</option>
                <option value="manager">manager</option>
                <option value="employee">employee</option>
              </select>
              <button
                className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50"
                disabled={addingUser}
              >
                {addingUser ? "Saving…" : "Add"}
              </button>
              <p className="text-xs text-slate-500">
                If email or password is left empty, credentials are
                auto-generated for BizzGrow.
              </p>
            </form>
          ) : (
            <p className="mt-3 text-xs text-slate-500">
              Only admin can manage user roles.
            </p>
          )}

          {lastCreatedCredentials && (
            <div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-900">
              <p className="font-semibold">Created user credentials</p>
              <p>Email: {lastCreatedCredentials.email}</p>
              <p>Password: {lastCreatedCredentials.password}</p>
              <p>
                Mode:{" "}
                {lastCreatedCredentials.autoGeneratedEmail
                  ? "auto email"
                  : "custom email"}
                ,{" "}
                {lastCreatedCredentials.autoGeneratedPassword
                  ? "auto password"
                  : "custom password"}
              </p>
            </div>
          )}

          <ul className="mt-3 space-y-2 text-sm">
            {loading
              ? Array.from({ length: 3 }).map((_, i) => (
                  <li
                    key={i}
                    className="animate-pulse rounded-lg bg-slate-200 px-3 py-4"
                  />
                ))
              : users.map((user) => {
                  const selectedRole = roleDrafts[user.id] || user.role;
                  const roleDirty = selectedRole !== user.role;

                  return (
                    <li
                      key={user.id}
                      className="rounded-lg bg-slate-50 px-3 py-2"
                    >
                      <div className="mb-2">
                        <span className="font-medium">{user.name}</span> -{" "}
                        {user.email}
                      </div>
                      <div className="flex flex-wrap items-center gap-2">
                        <select
                          className="rounded-md border border-slate-300 bg-white px-2 py-1 text-xs"
                          value={selectedRole}
                          onChange={(event) =>
                            setRoleDrafts((prev) => ({
                              ...prev,
                              [user.id]: event.target.value as Role,
                            }))
                          }
                          disabled={
                            savingRoleUserId === user.id ||
                            resettingPasswordUserId === user.id
                          }
                        >
                          <option value="admin">admin</option>
                          <option value="manager">manager</option>
                          <option value="employee">employee</option>
                        </select>
                        <button
                          className="rounded-md bg-slate-900 px-2 py-1 text-xs font-semibold text-white disabled:opacity-50"
                          onClick={() => saveUserRole(user)}
                          disabled={
                            !roleDirty ||
                            savingRoleUserId === user.id ||
                            resettingPasswordUserId === user.id
                          }
                        >
                          {savingRoleUserId === user.id
                            ? "Saving..."
                            : "Save role"}
                        </button>
                        <button
                          className="rounded-md bg-amber-100 px-2 py-1 text-xs font-semibold text-amber-900 disabled:opacity-50"
                          onClick={() => resetUserPassword(user)}
                          disabled={
                            savingRoleUserId === user.id ||
                            resettingPasswordUserId === user.id
                          }
                        >
                          {resettingPasswordUserId === user.id
                            ? "Resetting..."
                            : "Reset password"}
                        </button>
                        <button
                          className="rounded-md bg-rose-100 px-2 py-1 text-xs font-semibold text-rose-700 disabled:opacity-50"
                          onClick={() => deleteUser(user)}
                          disabled={
                            savingRoleUserId === user.id ||
                            resettingPasswordUserId === user.id ||
                            deletingUserId === user.id
                          }
                        >
                          {deletingUserId === user.id ? "Deleting..." : "Delete"}
                        </button>
                      </div>
                    </li>
                  );
                })}
          </ul>
        </section>
      </div>

      {canManageUsers && (
        <section className="mt-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
          <h3 className="text-base font-semibold">Audit Logs</h3>
          <ul className="mt-3 space-y-2 text-xs text-slate-700">
            {loading
              ? Array.from({ length: 4 }).map((_, i) => (
                  <li
                    key={i}
                    className="animate-pulse rounded bg-slate-200 px-3 py-3"
                  />
                ))
              : auditLogs.slice(0, 12).map((entry) => (
                  <li key={entry.id} className="rounded bg-slate-50 px-3 py-2">
                    <span className="font-semibold">{entry.action}</span> by{" "}
                    {entry.actor_email} - {entry.details}
                  </li>
                ))}
          </ul>
        </section>
      )}
    </AppShell>
  );
}
