import { fail, ok, parseZodError } from "@/lib/api";
import { createUserSchema } from "@/lib/schemas";
import { createRow, listRows } from "@/lib/db";
import { getSession, requirePermission } from "@/lib/auth";
import { User } from "@/lib/types";
import { normalizeEmail, generatePassword } from "@/lib/security";
import { createAdminClient } from "@/lib/supabase/server";
import { logAuditEvent } from "@/lib/audit";
import { sendWelcomeEmail } from "@/lib/mail";

const COMPANY_DOMAIN = "bizzgrowlabs.com";

function sanitizeUser(user: User) {
  return {
    id: user.id,
    name: user.name,
    email: user.email,
    role: user.role,
    created_at: user.created_at,
  };
}

function buildGeneratedEmail(existingEmails: Set<string>): string {
  let sequence = 0;

  while (true) {
    const localPart = sequence === 0 ? "user" : `user${sequence}`;
    const candidate = `${localPart}@${COMPANY_DOMAIN}`;
    if (!existingEmails.has(candidate)) {
      return candidate;
    }

    sequence += 1;
  }
}

export async function GET(request: Request) {
  const role = await requirePermission("manageUsers");
  if (role instanceof Response) {
    return role;
  }

  const rows = await listRows<User>("users");
  return ok({ role, data: rows.map(sanitizeUser) });
}

export async function POST(request: Request) {
  const role = await requirePermission("manageUsers");
  if (role instanceof Response) {
    return role;
  }

  const session = await getSession();
  if (!session) {
    return fail("Authentication required", 401);
  }

  try {
    const body = await request.json();
    const parsed = createUserSchema.parse(body);
    const existingUsers = await listRows<User>("users");
    const existingEmails = new Set(existingUsers.map((user) => normalizeEmail(user.email || "")).filter(Boolean));

    const autoGeneratedEmail = !parsed.email;
    const email = parsed.email ? normalizeEmail(parsed.email) : buildGeneratedEmail(existingEmails);

    if (existingEmails.has(email)) {
      return fail("email: A user with this email already exists", 400);
    }

    const autoGeneratedPassword = !parsed.password;
    const plainPassword = parsed.password ?? generatePassword();

    const adminClient = createAdminClient();

    const { data: authData, error: authError } = await adminClient.auth.admin.createUser({
      email: email,
      password: plainPassword,
      email_confirm: true,
      user_metadata: { name: parsed.name }
    });

    if (authError) {
      return fail(`Supabase Auth Error: ${authError.message}`, 400);
    }
    
    if (!authData.user) {
      return fail("Failed to create user in Auth", 500);
    }

    const { data: updatedProfile, error: profileError } = await adminClient.from("users").update({
      role: parsed.role,
      must_change_password: true,
    }).eq("id", authData.user.id).select().single();

    if (profileError) {
      return fail(`Failed to finalize user profile: ${profileError.message}`, 500);
    }

    const created = updatedProfile as User;

    await logAuditEvent({
      action: "user_created",
      actorEmail: session.email,
      actorRole: session.role,
      targetUserId: created.id,
      targetUserEmail: created.email,
      details: `Assigned role ${created.role}`,
    });

    // Send Welcome Email
    try {
      await sendWelcomeEmail(email, parsed.name, {
        email,
        password: plainPassword,
      });
    } catch (mailError) {
      console.error("Failed to send welcome email:", mailError);
      // We don't fail the request because the user is already created
    }

    return ok(
      {
        role,
        data: sanitizeUser(created),
        credentials: {
          email,
          password: plainPassword,
          autoGeneratedEmail,
          autoGeneratedPassword,
        },
      },
      201,
    );
  } catch (error) {
    return fail(parseZodError(error), 400);
  }
}
