import { fail, ok, parseZodError } from "@/lib/api";
import { createUserSchema } from "@/lib/schemas";
import { createRow, listRows } from "@/lib/db";
import { getSessionFromRequest, requirePermission } from "@/lib/auth";
import { User } from "@/lib/types";
import { generatePassword, hashPassword, normalizeEmail } from "@/lib/security";
import { logAuditEvent } from "@/lib/audit";

const COMPANY_DOMAIN = "bizzgrow.com";

function sanitizeUser(user: User) {
  return {
    id: user.id,
    name: user.name,
    email: user.email,
    role: user.role,
    created_at: user.created_at,
  };
}

function buildGeneratedEmail(existingEmails: Set<string>): string {
  let sequence = 0;

  while (true) {
    const localPart = sequence === 0 ? "user" : `user${sequence}`;
    const candidate = `${localPart}@${COMPANY_DOMAIN}`;
    if (!existingEmails.has(candidate)) {
      return candidate;
    }

    sequence += 1;
  }
}

export async function GET(request: Request) {
  const role = requirePermission(request, "read");
  if (role instanceof Response) {
    return role;
  }

  const rows = await listRows<User>("users");
  return ok({ role, data: rows.map(sanitizeUser) });
}

export async function POST(request: Request) {
  const role = requirePermission(request, "manageUsers");
  if (role instanceof Response) {
    return role;
  }

  const session = getSessionFromRequest(request);
  if (!session) {
    return fail("Authentication required", 401);
  }

  try {
    const body = await request.json();
    const parsed = createUserSchema.parse(body);
    const existingUsers = await listRows<User>("users");
    const existingEmails = new Set(existingUsers.map((user) => normalizeEmail(user.email || "")).filter(Boolean));

    const autoGeneratedEmail = !parsed.email;
    const email = parsed.email ? normalizeEmail(parsed.email) : buildGeneratedEmail(existingEmails);

    if (existingEmails.has(email)) {
      return fail("email: A user with this email already exists", 400);
    }

    const autoGeneratedPassword = !parsed.password;
    const plainPassword = parsed.password ?? generatePassword();

    const created = await createRow<User>("users", {
      name: parsed.name,
      email,
      password_hash: hashPassword(plainPassword),
      must_change_password: true,
      role: parsed.role,
    });

    await logAuditEvent({
      action: "user_created",
      actorEmail: session.email,
      actorRole: session.role,
      targetUserId: created.id,
      targetUserEmail: created.email,
      details: `Assigned role ${created.role}`,
    });

    return ok(
      {
        role,
        data: sanitizeUser(created),
        credentials: {
          email,
          password: plainPassword,
          autoGeneratedEmail,
          autoGeneratedPassword,
        },
      },
      201,
    );
  } catch (error) {
    return fail(parseZodError(error), 400);
  }
}
